# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: python:3.7

ipblock-ipcn:
  stage: build
  script:
    - python get-netblock-cn.py
  only:
    - master
  tags:
    - docker-machine
  artifacts:
    paths:
      - ipcn/*
