# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: generate
          command: |
            python get-netblock-cn.py
            sh init-ip2location-db.sh
            python get-netblock-cdn.py

      - store_artifacts:
          path: ~/repo/ipcn
          destination: ipcn

      - store_artifacts:
          path: ~/repo/ipcdn
          destination: ipcdn

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers: #use the triggers key to indicate a scheduled build
      - schedule:
          cron: "0 0 * * *" # use cron syntax to set the schedule
          filters:
            branches:
              only:
                - master
    jobs:
      - build
