name: nightlybuild

on:
  push:
    branches: 
      - master
      - release/*
  schedule:
    - cron: "28 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pipenv install netaddr
    - name: fetch-data
      run: |
        pipenv run python get-netblock-cn.py
        sh init-ip2location-db.sh
        pipenv run python get-netblock-cdn.py
        pipenv run python get-netblock-cloud.py
        mkdir public
        mv ipcn public/
        mv ipcdn public/
        mv ipcloud public/
        find public -name "*.json" -delete
        sh sort_files.sh
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: archive
        PUBLISH_DIR: ./public
      with:
        emptyCommits: false
